create table if not exists public.social_posts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  platform text not null,
  title text,
  content text,
  status text not null default 'draft'
);
